@url=http://localhost:3000/api/user/
@json=Content-Type: application/json

### 
get {{url}}/user

### 用户注册
post {{url}}/register
{{json}}

{
  "userName": "yaogengzhu",
  "passWord": "123456"
}


### 用户登录
post {{url}}/login
{{json}}

{
  "userName": "yaogengzhu",
  "passWord": "123456"
}

### 用户信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.4oN4QBQrzZSWBOHR3A3HNI9HUu-zsbqtjSP0ekngtx0