@url=http://localhost:3000/api/user/
@json=Content-Type: application/json

### 
get {{url}}/user

### 用户注册
post {{url}}/register
{{json}}

{
  "userName": "yaogengzhuxx",
  "passWord": "123456"
}


### 用户登录
post {{url}}/login
{{json}}

{
  "userName": "yaogengzhu",
  "passWord": "123456"
}

### 用户信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczODY5MjIyfQ.kbKQM3asjz5kWXtBPpCBCwE4tBjIk8wNMqTX07PVgk4


### 更改用户信息
post {{url}}/updateUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczODY5MjIyfQ.kbKQM3asjz5kWXtBPpCBCwE4tBjIk8wNMqTX07PVgk4
{{json}}

{
  "userName": "tes11t",
  "id": 2,
  "phone": "15871602731",
  "email": "ttttttt@qq.com"
}

### 获取用户列表
get {{url}}/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczODY5MjIyfQ.kbKQM3asjz5kWXtBPpCBCwE4tBjIk8wNMqTX07PVgk4
